In [3]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt
import seaborn as sns

In [4]:
from nba_api.stats.static import teams, players
from nba_api.stats.endpoints import commonallplayers

# Get team ID for the Toronto Raptors
team_dict = teams.get_teams()
raptors = [team for team in team_dict if team['abbreviation'] == 'TOR'][0]
raptors_id = raptors['id']

In [5]:
# Fetch all players for the Toronto Raptors
players = commonallplayers.CommonAllPlayers(is_only_current_season=1, league_id='00', season='2023-24')
players_df = players.get_data_frames()[0]

# Display the list of players
print("Players in the 2023-2024 NBA Season:")
print(players_df[['PERSON_ID', 'DISPLAY_FIRST_LAST']])

Players in the 2023-2024 NBA Season:
     PERSON_ID DISPLAY_FIRST_LAST
0      1630173   Precious Achiuwa
1       203500       Steven Adams
2      1628389        Bam Adebayo
3      1630534       Ochai Agbaji
4      1630583       Santi Aldama
..         ...                ...
556     201152     Thaddeus Young
557    1629027         Trae Young
558    1630209     Omer Yurtseven
559     203469        Cody Zeller
560    1627826        Ivica Zubac

[561 rows x 2 columns]

In [6]:
# Now Filter for NBA players on the raptors

raptors_players = players_df[players_df['TEAM_ID'] == raptors_id]

raptors_players.head(10)

,PERSON_ID,DISPLAY_LAST_COMMA_FIRST,DISPLAY_FIRST_LAST,ROSTERSTATUS,FROM_YEAR,TO_YEAR,PLAYERCODE,PLAYER_SLUG,TEAM_ID,TEAM_CITY,TEAM_NAME,TEAM_ABBREVIATION,TEAM_SLUG,TEAM_CODE,GAMES_PLAYED_FLAG,OTHERLEAGUE_EXPERIENCE_CH
3,1630534,"Agbaji, Ochai",Ochai Agbaji,1,2022,2023,ochai_agbaji,ochai_agbaji,1610612761,Toronto,Raptors,TOR,raptors,raptors,Y,00
30,1630567,"Barnes, Scottie",Scottie Barnes,1,2021,2023,scottie_barnes,scottie_barnes,1610612761,Toronto,Raptors,TOR,raptors,raptors,Y,00
31,1629628,"Barrett, RJ",RJ Barrett,1,2019,2023,rj_barrett,rj_barrett,1610612761,Toronto,Raptors,TOR,raptors,raptors,Y,00
55,1628449,"Boucher, Chris",Chris Boucher,1,2017,2023,chris_boucher,chris_boucher,1610612761,Toronto,Raptors,TOR,raptors,raptors,Y,01
66,1628971,"Brown, Bruce",Bruce Brown,1,2018,2023,bruce_brown,bruce_brown,1610612761,Toronto,Raptors,TOR,raptors,raptors,Y,01
88,1630618,"Carton, D.J.",D.J. Carton,1,2023,2023,dj_carton,dj_carton,1610612761,Toronto,Raptors,TOR,raptors,raptors,Y,11
125,1641711,"Dick, Gradey",Gradey Dick,1,2023,2023,gradey_dick,gradey_dick,1610612761,Toronto,Raptors,TOR,raptors,raptors,Y,11
155,1631241,"Freeman-Liberty, Javon",Javon Freeman-Liberty,1,2023,2023,javon_freeman-liberty,javon_freeman-liberty,1610612761,Toronto,Raptors,TOR,raptors,raptors,Y,11
326,1629667,"McDaniels, Jalen",Jalen McDaniels,1,2019,2023,jalen_mcdaniels,jalen_mcdaniels,1610612761,Toronto,Raptors,TOR,raptors,raptors,Y,01
372,1641806,"Nowell, Markquis",Markquis Nowell,1,2023,2023,markquis_nowell,markquis_nowell,1610612761,Toronto,Raptors,TOR,raptors,raptors,Y,11

In [13]:
from nba_api.stats.endpoints import playerdashboardbyyearoveryear

def get_player_stats(player_id):
    # Fetch player stats for the current season
    player_stats = playerdashboardbyyearoveryear.PlayerDashboardByYearOverYear(player_id=player_id)
    player_stats_df = player_stats.get_data_frames()[1]  # Index 1 contains per game stats
    
    # Filter stats for the 2023-2024 season
    player_stats_2023_2024 = player_stats_df[player_stats_df['GROUP_VALUE'] == '2023-24']

    desired_statistics = ['MIN', 'FG3_PCT', 'FG3M', 'FG3A', 'FG3_PCT_RANK']
    
    # Return the desired statistics
    return player_stats_2023_2024[desired_statistics]

In [36]:
# Print each player's 3 point goal percentage and their field goal percentage

raptors_stats = []
# Create an empty vector to store player names
player_names = []

for player_id in raptors_players['PERSON_ID']:
    player_info = raptors_players[raptors_players['PERSON_ID'] == player_id].iloc[0]
    player_name = player_info['DISPLAY_FIRST_LAST']

    player_stats = get_player_stats(player_id)

    print(f"\nPlayer: {player_name}")
    print(player_stats)

    player_names.extend([player_name]*len(player_stats))
    raptors_stats.append(player_stats)

Player: Ochai Agbaji
           MIN  FG3_PCT  FG3M  FG3A  FG3_PCT_RANK
0  1045.770000    0.318    48   151             1
1    42.383333    0.111     1     9             3
2  1003.386667    0.331    47   142             2

Player: Scottie Barnes
        MIN  FG3_PCT  FG3M  FG3A  FG3_PCT_RANK
0  1934.565    0.353    98   278             1

Player: RJ Barrett
           MIN  FG3_PCT  FG3M  FG3A  FG3_PCT_RANK
0  1406.313333    0.343    69   201             1
1   639.805000    0.366    26    71             2
2   766.508333    0.331    43   130             4

Player: Chris Boucher
       MIN  FG3_PCT  FG3M  FG3A  FG3_PCT_RANK
0  640.845    0.326    29    89             3

Player: Bruce Brown
           MIN  FG3_PCT  FG3M  FG3A  FG3_PCT_RANK
0  1345.323333    0.320    41   128             1
1   364.745000    0.296     8    27             5
2   980.578333    0.327    33   101             4

Player: D.J. Carton
Empty DataFrame
Columns: [MIN, FG3_PCT, FG3M, FG3A, FG3_PCT_RANK]
Index: []

Player: Gradey Dick
          MIN  FG3_PCT  FG3M  FG3A  FG3_PCT_RANK
0  519.761667    0.357    35    98             1

Player: Javon Freeman-Liberty
   MIN  FG3_PCT  FG3M  FG3A  FG3_PCT_RANK
0  3.9      0.0     0     0             1

Player: Jalen McDaniels
      MIN  FG3_PCT  FG3M  FG3A  FG3_PCT_RANK
0  295.13    0.208    11    53             6

Player: Markquis Nowell
        MIN  FG3_PCT  FG3M  FG3A  FG3_PCT_RANK
0  3.516667      0.0     0     0             1

Player: Jordan Nwora
          MIN  FG3_PCT  FG3M  FG3A  FG3_PCT_RANK
0  306.778333    0.345    20    58             2
1  124.266667    0.409     9    22             3
2  182.511667    0.306    11    36             6

Player: Kelly Olynyk
           MIN  FG3_PCT  FG3M  FG3A  FG3_PCT_RANK
0  1069.738333    0.418    38    91             1
1    50.483333    0.286     2     7            13
2  1019.255000    0.429    36    84             1

Player: Jakob Poeltl
           MIN  FG3_PCT  FG3M  FG3A  FG3_PCT_RANK
0  1176.948333      0.0     0     0             3

Player: Jontay Porter
          MIN  FG3_PCT  FG3M  FG3A  FG3_PCT_RANK
0  220.786667    0.324    12    37             2

Player: Immanuel Quickley
       MIN  FG3_PCT  FG3M  FG3A  FG3_PCT_RANK
0  1361.21    0.400   116   290             1
1   641.04    0.406    52   128             1
2   720.17    0.395    64   162             2

Player: Garrett Temple
         MIN  FG3_PCT  FG3M  FG3A  FG3_PCT_RANK
0  68.876667    0.222     2     9            16

Player: Gary Trent Jr.
       MIN  FG3_PCT  FG3M  FG3A  FG3_PCT_RANK
0  1312.87    0.418   119   285             2
['Ochai Agbaji', 'Ochai Agbaji', 'Ochai Agbaji', 'Scottie Barnes', 'RJ Barrett', 'RJ Barrett', 'RJ Barrett', 'Chris Boucher', 'Bruce Brown', 'Bruce Brown', 'Bruce Brown', 'Gradey Dick', 'Javon Freeman-Liberty', 'Jalen McDaniels', 'Markquis Nowell', 'Jordan Nwora', 'Jordan Nwora', 'Jordan Nwora', 'Kelly Olynyk', 'Kelly Olynyk', 'Kelly Olynyk', 'Jakob Poeltl', 'Jontay Porter', 'Immanuel Quickley', 'Immanuel Quickley', 'Immanuel Quickley', 'Garrett Temple', 'Gary Trent Jr.']

In [37]:
raptors_stats_df = pd.concat(raptors_stats, ignore_index=True)

raptors_stats_df.insert(0, 'Player Name', player_names)

raptors_stats_df.head(10)

      Player Name          MIN  FG3_PCT FG3M FG3A FG3_PCT_RANK
0    Ochai Agbaji  1045.770000    0.318   48  151            1
1    Ochai Agbaji    42.383333    0.111    1    9            3
2    Ochai Agbaji  1003.386667    0.331   47  142            2
3  Scottie Barnes  1934.565000    0.353   98  278            1
4      RJ Barrett  1406.313333    0.343   69  201            1
5      RJ Barrett   639.805000    0.366   26   71            2
6      RJ Barrett   766.508333    0.331   43  130            4
7   Chris Boucher   640.845000    0.326   29   89            3
8     Bruce Brown  1345.323333    0.320   41  128            1
9     Bruce Brown   364.745000    0.296    8   27            5