In [6]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt
import seaborn as sns

In [12]:
from nba_api.stats.static import teams, players
from nba_api.stats.endpoints import commonallplayers

# Get team ID for the Toronto Raptors
team_dict = teams.get_teams()
raptors = [team for team in team_dict if team['abbreviation'] == 'TOR'][0]
raptors_id = raptors['id']

In [17]:
# Fetch all players for the Toronto Raptors
players = commonallplayers.CommonAllPlayers(is_only_current_season=1, league_id='00', season='2023-24')
players_df = players.get_data_frames()[0]

# Display the list of players
print("Players in the 2023-2024 NBA Season:")
print(players_df[['PERSON_ID', 'DISPLAY_FIRST_LAST']])

Players in Toronto Raptors:
     PERSON_ID DISPLAY_FIRST_LAST
0      1630173   Precious Achiuwa
1       203500       Steven Adams
2      1628389        Bam Adebayo
3      1630534       Ochai Agbaji
4      1630583       Santi Aldama
..         ...                ...
551     201152     Thaddeus Young
552    1629027         Trae Young
553    1630209     Omer Yurtseven
554     203469        Cody Zeller
555    1627826        Ivica Zubac

[556 rows x 2 columns]

In [24]:
# Now Filter for NBA players on the raptors

raptors_players = players_df[players_df['TEAM_ID'] == raptors_id]

raptors_players.head(10)

,PERSON_ID,DISPLAY_LAST_COMMA_FIRST,DISPLAY_FIRST_LAST,ROSTERSTATUS,FROM_YEAR,TO_YEAR,PLAYERCODE,PLAYER_SLUG,TEAM_ID,TEAM_CITY,TEAM_NAME,TEAM_ABBREVIATION,TEAM_SLUG,TEAM_CODE,GAMES_PLAYED_FLAG,OTHERLEAGUE_EXPERIENCE_CH
3,1630534,"Agbaji, Ochai",Ochai Agbaji,1,2022,2023,ochai_agbaji,ochai_agbaji,1610612761,Toronto,Raptors,TOR,raptors,raptors,Y,00
30,1630567,"Barnes, Scottie",Scottie Barnes,1,2021,2023,scottie_barnes,scottie_barnes,1610612761,Toronto,Raptors,TOR,raptors,raptors,Y,00
31,1629628,"Barrett, RJ",RJ Barrett,1,2019,2023,rj_barrett,rj_barrett,1610612761,Toronto,Raptors,TOR,raptors,raptors,Y,00
55,1628449,"Boucher, Chris",Chris Boucher,1,2017,2023,chris_boucher,chris_boucher,1610612761,Toronto,Raptors,TOR,raptors,raptors,Y,01
66,1628971,"Brown, Bruce",Bruce Brown,1,2018,2023,bruce_brown,bruce_brown,1610612761,Toronto,Raptors,TOR,raptors,raptors,Y,01
88,1630618,"Carton, D.J.",D.J. Carton,1,2023,2023,dj_carton,dj_carton,1610612761,Toronto,Raptors,TOR,raptors,raptors,Y,11
123,1641711,"Dick, Gradey",Gradey Dick,1,2023,2023,gradey_dick,gradey_dick,1610612761,Toronto,Raptors,TOR,raptors,raptors,Y,11
153,1631241,"Freeman-Liberty, Javon",Javon Freeman-Liberty,1,2023,2023,javon_freeman-liberty,javon_freeman-liberty,1610612761,Toronto,Raptors,TOR,raptors,raptors,Y,11
322,1629667,"McDaniels, Jalen",Jalen McDaniels,1,2019,2023,jalen_mcdaniels,jalen_mcdaniels,1610612761,Toronto,Raptors,TOR,raptors,raptors,Y,01
368,1641806,"Nowell, Markquis",Markquis Nowell,1,2023,2023,markquis_nowell,markquis_nowell,1610612761,Toronto,Raptors,TOR,raptors,raptors,Y,11

In [25]:
from nba_api.stats.endpoints import playerdashboardbyyearoveryear

def get_player_stats(player_id):
    # Fetch player stats for the current season
    player_stats = playerdashboardbyyearoveryear.PlayerDashboardByYearOverYear(player_id=player_id)
    player_stats_df = player_stats.get_data_frames()[1]  # Index 1 contains per game stats
    
    # Filter stats for the 2023-2024 season
    player_stats_2023_2024 = player_stats_df[player_stats_df['GROUP_VALUE'] == '2023-24']
    
    # Return the desired statistics
    return player_stats_2023_2024[['FG3_PCT', 'FG_PCT',]]

In [33]:
# Print each player's 3 point goal percentage and their field goal percentage

for player_id in raptors_players['PERSON_ID']:
    player_info = raptors_players[raptors_players['PERSON_ID'] == player_id].iloc[0]
    player_name = player_info['DISPLAY_FIRST_LAST']
    player_stats = get_player_stats(player_id)
    print(f"\nPlayer: {player_name}")
    print(player_stats)

Player: Ochai Agbaji
   FG3_PCT  FG_PCT
0    0.318   0.416
1    0.111   0.278
2    0.331   0.426

Player: Scottie Barnes
   FG3_PCT  FG_PCT
0    0.353   0.473

Player: RJ Barrett
   FG3_PCT  FG_PCT
0    0.343   0.475
1    0.366   0.549
2    0.331   0.423

Player: Chris Boucher
   FG3_PCT  FG_PCT
0    0.326   0.493

Player: Bruce Brown
   FG3_PCT  FG_PCT
0    0.320   0.472
1    0.296   0.466
2    0.327   0.475

Player: D.J. Carton
Empty DataFrame
Columns: [FG3_PCT, FG_PCT]
Index: []

Player: Gradey Dick
   FG3_PCT  FG_PCT
0    0.357   0.403

Player: Javon Freeman-Liberty
   FG3_PCT  FG_PCT
0      0.0   0.333

Player: Jalen McDaniels
   FG3_PCT  FG_PCT
0    0.208   0.333

Player: Markquis Nowell
   FG3_PCT  FG_PCT
0      0.0     0.0

Player: Jordan Nwora
   FG3_PCT  FG_PCT
0    0.345   0.441
1    0.409   0.422
2    0.306   0.451

Player: Kelly Olynyk
   FG3_PCT  FG_PCT
0    0.418   0.556
1    0.286   0.476
2    0.429   0.562

Player: Jakob Poeltl
   FG3_PCT  FG_PCT
0      0.0   0.675

Player: Jontay Porter
   FG3_PCT  FG_PCT
0    0.324   0.371

Player: Immanuel Quickley
   FG3_PCT  FG_PCT
0    0.400   0.430
1    0.406   0.401
2    0.395   0.454

Player: Garrett Temple
   FG3_PCT  FG_PCT
0    0.222   0.381

Player: Gary Trent Jr.
   FG3_PCT  FG_PCT
0    0.418   0.416